export const TOTAL_STEPS = 6;
export const TRANSITION_DISTANCE = 80;
export const TRANSITION_DURATION = 480;
export const TRANSITION_FADE_DURATION = 360;
export const TRANSITION_START_SCALE = 0.94;
export const LOCATION_TIMEOUT_MS = 8000;
export const LAST_LOCATION_MAX_AGE_MS = 300000;
