export const FAJR_ISHA_ANGLE = 18;
export const SUNRISE_SUNSET_ALTITUDE = -0.833;
export const STANDARD_ASR_SHADOW_FACTOR = 1;
export const SHORT_ASR_WINDOW_MINUTES = 45;
export const TIMETABLE_SAFETY_MINUTES = 4;
export const HIGH_LATITUDE_ISHA_AFTER_MAGHRIB_MINUTES = 75;
